name: flira
description: A tool to report Jira issues from any flutter-app. It can be activated by shaking the phone or taking a screenshot.
version: 0.3.23
publish_to: none
homepage: https://github.com/MarcosTort/flira
environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  atlassian_apis: ^0.11.0
  equatable: ^2.0.5
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  jira_repository:
    path: packages/jira_repository/
  flutter_secure_storage: ^7.0.1
  permission_handler: ^10.2.0
  screenshot_callback: ^2.0.3
  shake: ^2.2.0
  # screenshot_callback: ^2.0.3
  # shake: ^2.2.0  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  
flutter:
