name: flira
description: A tool to report Jira issues from any flutter-app. It can be activated by shaking the phone or taking a screenshot.
version: 0.3.0
homepage: https://github.com/MarcosTort/flira
environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  atlassian_apis: ^0.8.0
  bloc: ^8.1.0
  equatable: ^2.0.5
  file_picker: ^5.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^6.0.0
  permission_handler: ^10.0.2
  screenshot_callback: ^2.0.3
  shake: ^2.1.0  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
