name: jira_repository
description: JiraRepository pure dart package.
version: 0.0.1

environment: 
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  atlassian_apis: ^0.11.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0