# .github/workflows/generate-tests.yml
name: 🧪 Generate Flutter Tests

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Rama para generar tests'
        required: true
        type: string
      lm_studio_url:
        description: 'URL de LM Studio'
        required: false
        default: 'http://192.168.1.7:8080'
        type: string

jobs:
  generate-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - run: scripts/run_test_generator.sh "${{ inputs.target_branch }}" "${{ inputs.lm_studio_url }}"
